### ISSUE TITLE
Bug- Companion "Deshavi" has purple skin below the neck "WARNING: unable to find material You_can't_be_serious!" red text pops up

### ISSUE THREAD

**Issue by WHYDONTYOULIKETHEPIECEAPIE** [LilyModzStuff/warband_mod_source#64] opened 2018-10-08 15:18 UTC
Interesting bug! is she supposed to be naked?

other bugs include using the cheat menu to "find item" some clothing and armor items simply turn parts of the player invisible. Also, are there any clothes that actually allow the player to reveal themselves like walk around naked in any setting, O doesn't work mid battle. not sure if that's a bug too or not.

Another bug is that normally pressing O would make armor disappear and then show the underwear (white towel things) and pressing again would make the character naked, but now pressing O goes straight to naked without showing the underwear first. Interesting bugs.

**Comment by LilyModzStuff** [comment] 2018-10-08 17:14
@WHYDONTYOULIKETHEPIECEAPIE 

1.) Deshavi's body stuff is mostly fixed in the latest version with the exception of skin color in LOD (but that issue is already opened.) 
2.) Find item cheat menu is not supported due to the nature of the mod, and the fact that you aren't supposed to see most of those items in the mod which have been causing issues since the original Dickplomacy. 
3.) Female character is nude by default in the new version so that isn't an issue in the latest nightly patch on the devel branch. 
4.) It doesn't work in mid battle because it is only setup to work in peaceful scenes but I could see about adding it to battles but I don't know if it would work.

**Closed by LilyModzStuff** 2018-10-08 17:14 UTC

**Comment by WHYDONTYOULIKETHEPIECEAPIE** [comment] 2018-10-09 12:39
@LilyModzStuff all the problems I'm reporting are coming from the latest patch, there are female characters wearing underwear by default, and not naked, and the game flip flops back and forth and can't make up it's mind on whether to leave them naked or underwear. it's very glitchy.

**Comment by LilyModzStuff** [comment] 2018-10-09 13:42
@WHYDONTYOULIKETHEPIECEAPIE the nightly devel branch isn't on loverslab, it's only on the github, did you compile from source? If you did then I know the issue is with the script.

**Comment by WHYDONTYOULIKETHEPIECEAPIE** [comment] 2018-10-11 03:48
@LilyModzStuff No I downloaded from loverslab. I didn't know there was a full version of the mod at a higher version level anywhere else. Is it the same way? just drop into the mod folder? or do I have to compile myself? I'm scared lol.

**Comment by cyman501** [comment] 2024-05-23 13:41
me too; it happened when set compaine auto-loot, especially in the 2nd slot of weapon. when it set to polearms
